name: Release

on:
  push:
    branches:
      - test-gha-221106
  workflow_dispatch:
    inputs:
      manual_release:
        description: "Manually trigger doc build and release."
        required: false
        default: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "tkn: $GITHUB_TOKEN"
          gh repo fork --clone Kapeli/Dash-User-Contributions
          ls -a ./Dash-User-Contributions

      - name: Branch
        working-directory: ./Dash-User-Contributions
        run: |
          git remote -v
          git switch --create=${{ github.run_id }}-${{ github.run_attempt }}
          git status

      - name: Make a change
        working-directory: ./Dash-User-Contributions
        run: |
          echo 'change\n' > file.txt

      - name: Setup git
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          global: true
          name: Tester testy
          email: tester@testit.com
          actor: paw-lu

      - name: Log git cred config
        working-directory: ./Dash-User-Contributions
        run: |
          git config --global --list
          echo "github actor: ${{ github.actor }}"
          echo "GIT_USER: $GIT_USER"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git status

      - name: Commit
        working-directory: ./Dash-User-Contributions
        run: |
          git remote -v
          git add --all
          git commit --message="Change!"
          git status

      - name: Push
        working-directory: ./Dash-User-Contributions
        env:
          GIT_USER: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GH_TOKEN }}
        run: |
          GIT_USER="${{ secrets.GH_TOKEN }}"
          GITHUB_ACTOR="${{ secrets.GH_TOKEN }}"
          git config credential.helper store
          echo https://OleksiyRudenko:${{ secrets.GH_TOKEN }}@https://github.com > .git-credentials
          echo "GIT_USER: $GIT_USER"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git remote -v
          git push --set-upstream origin ${{ github.run_id }}-${{ github.run_attempt }}
